export const UPDATE_PROTO_PATH = 'UPDATE_PROTO_PATH';
export const CLEAN_APP_CACHE = 'CLEAN_APP_CACHE';

export const TOGGLE_PROTO_ENABLED = 'TOGGLE_PROTO_ENABLED';
export const UPDATE_KAFKA_HOST = 'UPDATE_KAFKA_HOST';
export const UPDATE_KAFKA_TOPIC = 'UPDATE_KAFKA_TOPIC';
