export const UPDATE_PROTO_PATH = 'UPDATE_PROTO_PATH';
export const UPDATE_MESSAGE = 'UPDATE_MESSAGE';
export const CLEAN_APP_CACHE = 'CLEAN_APP_CACHE';
export const TOGGLE_IS_CONSUMER_CONNECTING = 'TOGGLE_IS_CONSUMER_CONNECTING';
export const SIDE_BAR_ITEM_SELECT = 'SIDE_BAR_ITEM_SELECT';
export const UPDATE_ERROR = 'UPDATE_ERROR';

export const TOGGLE_PROTO_ENABLED = 'TOGGLE_PROTO_ENABLED';
export const UPDATE_KAFKA_HOST = 'UPDATE_KAFKA_HOST';
export const UPDATE_KAFKA_TOPIC = 'UPDATE_KAFKA_TOPIC';
